#!/usr/bin/env python3
"""
Converts a Game Boy .gb ROM file into a rom.c source file that gets
compiled directly into the Pico firmware. Run this before building.

Usage:
    python make_rom.py path\to\game.gb

Output:
    SRC/Pico-GB-20250207/src/rom.c
"""

import sys
import os

if len(sys.argv) != 2:
    print("Usage: python make_rom.py path\\to\\game.gb")
    sys.exit(1)

rom_path = sys.argv[1]
if not os.path.exists(rom_path):
    print(f"Error: file not found: {rom_path}")
    sys.exit(1)

with open(rom_path, "rb") as f:
    data = f.read()

out_path = os.path.join(
    os.path.dirname(__file__),
    "SRC", "Pico-GB-20250207", "src", "rom.c"
)

with open(out_path, "w") as f:
    f.write("/* Auto-generated by make_rom.py — do not edit manually. */\n")
    f.write('#include "pico/platform.h"\n\n')
    f.write('const unsigned char __in_flash("rom") rom_data[] = {\n')
    for i, byte in enumerate(data):
        if i % 16 == 0:
            f.write("    ")
        f.write(f"0x{byte:02x},")
        if i % 16 == 15:
            f.write("\n")
        else:
            f.write(" ")
    if len(data) % 16 != 0:
        f.write("\n")
    f.write("};\n\n")
    f.write(f"const unsigned int rom_data_len = {len(data)};\n")

print(f"Done! ROM: {os.path.basename(rom_path)} ({len(data):,} bytes)")
print(f"Written to: {out_path}")
print("Now rebuild the firmware.")
